#pragma checksum "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\WebCollection\ProductPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "022ec35b63f8f207dd88be2d416e05f152711a51"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_WebCollection_ProductPage), @"mvc.1.0.view", @"/Views/WebCollection/ProductPage.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/WebCollection/ProductPage.cshtml", typeof(AspNetCore.Views_WebCollection_ProductPage))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\_ViewImports.cshtml"
using YouStore;

#line default
#line hidden
#line 2 "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\_ViewImports.cshtml"
using YouStore.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"022ec35b63f8f207dd88be2d416e05f152711a51", @"/Views/WebCollection/ProductPage.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"4d9113c5516be5079b85800b0929919b1f970f4a", @"/Views/_ViewImports.cshtml")]
    public class Views_WebCollection_ProductPage : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Models.Product>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("productimg"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("alt", new global::Microsoft.AspNetCore.Html.HtmlString("Denim Jeans"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(23, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 3 "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\WebCollection\ProductPage.cshtml"
  
    ViewData["Title"] = "ProductPage";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";

#line default
#line hidden
            BeginContext(125, 12, true);
            WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n");
            EndContext();
            BeginContext(137, 674, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "022ec35b63f8f207dd88be2d416e05f152711a514541", async() => {
                BeginContext(143, 32, true);
                WriteLiteral("\r\n\r\n    <h1 class=\"ProductName\">");
                EndContext();
                BeginContext(176, 43, false);
#line 15 "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\WebCollection\ProductPage.cshtml"
                       Write(Html.DisplayFor(model => model.ProductName));

#line default
#line hidden
                EndContext();
                BeginContext(219, 26, true);
                WriteLiteral("</h1>\r\n    <div>\r\n        ");
                EndContext();
                BeginContext(245, 107, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "022ec35b63f8f207dd88be2d416e05f152711a515401", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                AddHtmlAttributeValue("", 274, "~/images/", 274, 9, true);
#line 17 "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\WebCollection\ProductPage.cshtml"
AddHtmlAttributeValue("", 283, Html.DisplayFor(model => model.Productimagelink), 283, 49, false);

#line default
#line hidden
                EndAddHtmlAttributeValues(__tagHelperExecutionContext);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(352, 59, true);
                WriteLiteral("\r\n    </div>\r\n    <div class=\"price\">\r\n        <p> PRIJS: $");
                EndContext();
                BeginContext(412, 44, false);
#line 20 "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\WebCollection\ProductPage.cshtml"
               Write(Html.DisplayFor(model => model.ProductPrijs));

#line default
#line hidden
                EndContext();
                BeginContext(456, 53, true);
                WriteLiteral("</p>\r\n    </div>\r\n    <div class=\"Desc\">\r\n        <p>");
                EndContext();
                BeginContext(510, 50, false);
#line 23 "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\WebCollection\ProductPage.cshtml"
      Write(Html.DisplayFor(model => model.ProductDescription));

#line default
#line hidden
                EndContext();
                BeginContext(560, 94, true);
                WriteLiteral("</p>\r\n    </div>\r\n\r\n    <div>\r\n        <button type=\"button\" class=\"Buy btn-danger glyphicon \"");
                EndContext();
                BeginWriteAttribute("onclick", " onclick=\"", 654, "\"", 770, 3);
                WriteAttributeValue("", 664, "location.href=\'/ShoppingBasket/AddProductsToShoppingBasket/id?=", 664, 63, true);
#line 27 "C:\Users\Sam\Desktop\S2 software\YouStore-Local databse\YouStore\Views\WebCollection\ProductPage.cshtml"
WriteAttributeValue("", 727, Html.DisplayFor(model => model.ProductId), 727, 42, false);

#line default
#line hidden
                WriteAttributeValue("", 769, "\'", 769, 1, true);
                EndWriteAttribute();
                BeginContext(771, 33, true);
                WriteLiteral(">Add</button>\r\n    </div>\r\n\r\n\r\n\r\n");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(811, 577, true);
            WriteLiteral(@"

<style>
    .productimg {
        width: 28%;
        height: 53%;
        padding-bottom: 10px;
        margin-bottom: -483px;
    }

    .Desc {
        padding-left: 30px;
        padding-top: 10px;
        padding-left: 682px;
        color: brown;
        font-size: 22px;
    }

    .ProductName {
        padding-left: 20px;
        margin-top: 15px;
    }

    .price {
        padding-left: 694px;
        color: grey;
        font-size: 22px;
    }

    .Buy {
        margin-left: 732px;
        font-size: 20px;
    }
</style>

");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Models.Product> Html { get; private set; }
    }
}
#pragma warning restore 1591
